reddit_base_image_slim/postmill_app/src/Entity/Forum.php
<?php

namespace App\Entity;

use App\Entity\Contracts\BackgroundImageInterface as BackgroundImage;
use App\Entity\Contracts\DomainEventsInterface as DomainEvents;
use App\Event\ForumDeleted;
use App\Event\ForumUpdated;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Selectable;
use Doctrine\ORM\Mapping as ORM;
use Pagerfanta\Doctrine\Collections\CollectionAdapter;
use Pagerfanta\Doctrine\Collections\SelectableAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Contracts\EventDispatcher\Event;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ForumRepository")
 * @ORM\Table(indexes={
 *     @ORM\Index(name="forum_featured_idx", columns={"featured"}),
 *     @ORM\Index(name="forums_light_background_image_id_idx", columns={"light_background_image_id"}),
 *     @ORM\Index(name="forums_dark_background_image_id_idx", columns={"dark_background_image_id"}),
 * }, uniqueConstraints={
 *     @ORM\UniqueConstraint(name="forums_name_idx", columns={"name"}),
 *     @ORM\UniqueConstraint(name="forums_normalized_name_idx", columns={"normalized_name"}),
 * })
 */
class Forum implements BackgroundImage, DomainEvents {
    /**
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Id()
     *
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string
     */
    private $name;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string
     */
    private $normalizedName;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string|null
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string
     */
    private $sidebar;

    /**
     * @ORM\OneToMany(targetEntity="Moderator", mappedBy="forum", cascade={"persist", "remove"})
     *
     * @var Collection<array-key, Moderator>&Selectable<array-key, Moderator>
     */
    private $moderators;

    /**
     * @ORM\OneToMany(targetEntity="Submission", mappedBy="forum", cascade={"remove"}, fetch="EXTRA_LAZY")
     *
     * @var Collection<array-key, Submission>&Selectable<array-key, Submission>
     */
    private $submissions;

    /**
     * @ORM\Column(type="datetimetz_immutable")
     *
     * @var \DateTimeImmutable
     */
    private $created;

    /**
     * @ORM\OneToMany(targetEntity="ForumSubscription", mappedBy="forum",
     *     cascade={"persist", "remove"}, orphanRemoval=true, fetch="EXTRA_LAZY")
     *
     * @var Collection<array-key, ForumSubscription>&Selectable<array-key, ForumSubscription>
     */
    private $subscriptions;

    /**
     * @ORM\OneToMany(targetEntity="ForumBan", mappedBy="forum", cascade={"persist", "remove"})
     *
     * @var Collection<array-key, ForumBan>&Selectable<array-key, ForumBan>
     */
    private $bans;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $featured = false;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     *
     * @var bool
     */
    private $moderationLogPublic = true;

    /**
     * @ORM\JoinTable(name="forums_tags", joinColumns={
     *     @ORM\JoinColumn(name="forum_id", referencedColumnName="id"),
     * }, inverseJoinColumns={
     *     @ORM\JoinColumn(name="tag_id", referencedColumnName="id"),
     * })
     * @ORM\ManyToMany(targetEntity="ForumTag", inversedBy="forums", cascade={"persist"}, fetch="EXTRA_LAZY")
     *
     * @var Collection<array-key, ForumTag>&Selectable<array-key, ForumTag>
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="Image", cascade={"persist"})
     *
     * @var Image|null
     */
    private $lightBackgroundImage;

    /**
     * @ORM\ManyToOne(targetEntity="Image", cascade={"persist"})
     *
     * @var Image|null
     */
    private $darkBackgroundImage;

    /**
     * @ORM\Column(type="text", options={"default": BackgroundImage::BACKGROUND_TILE})
     *
     * @var string
     */
    private $backgroundImageMode = BackgroundImage::BACKGROUND_TILE;

    /**
     * @ORM\JoinColumn(onDelete="SET NULL")
     * @ORM\ManyToOne(targetEntity="Theme")
     *
     * @var Theme|null
     */
    private $suggestedTheme;

    /**
     * @ORM\OneToMany(targetEntity="ForumLogEntry", mappedBy="forum", cascade={"persist", "remove"})
     * @ORM\OrderBy({"timestamp": "DESC"})
     *
     * @var Collection<array-key, ForumLogEntry>&Selectable<array-key, ForumLogEntry>
     */
    private $logEntries;

    public function __construct(
        string $name,
        string $title,
        string $description,
        string $sidebar,
        User $user = null
    ) {
        $this->setName($name);
        $this->title = $title;
        $this->description = $description;
        $this->sidebar = $sidebar;
        $this->created = new \DateTimeImmutable('@'.time());
        $this->tags = new ArrayCollection();
        $this->bans = new ArrayCollection();
        $this->moderators = new ArrayCollection();
        $this->submissions = new ArrayCollection();
        $this->subscriptions = new ArrayCollection();
        $this->logEntries = new ArrayCollection();

        if ($user) {
            $this->addModerator(new Moderator($this, $user));
            $this->subscribe($user);
        }
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getName(): string {
        return $this->name;
    }

    public function setName(string $name): void {
        $this->name = $name;
        $this->normalizedName = self::normalizeName($name);
    }

    public function getNormalizedName(): ?string {
        return $this->normalizedName;
    }

    public function getTitle(): string {
        return $this->title;
    }

    public function setTitle(string $title): void {
        $this->title = $title;
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    public function setDescription(?string $description): void {
        $this->description = $description;
    }

    public function getSidebar(): string {
        return $this->sidebar;
    }

    public function setSidebar(string $sidebar): void {
        $this->sidebar = $sidebar;
    }

    /**
     * @return array<Moderator>
     */
    public function getModerators(): array {
        return $this->moderators->getValues();
    }

    /**
     * @return Pagerfanta<Moderator>
     */
    public function getPaginatedModerators(int $page, int $maxPerPage = 25): Pagerfanta {
        $criteria = Criteria::create()->orderBy(['timestamp' => 'ASC']);

        $moderators = new Pagerfanta(new SelectableAdapter($this->moderators, $criteria));
        $moderators->setMaxPerPage($maxPerPage);
        $moderators->setCurrentPage($page);

        return $moderators;
    }

    public function userIsModerator($user, bool $adminsAreMods = true): bool {
        if (!$user instanceof User) {
            return false;
        }

        if ($adminsAreMods && $user->isAdmin()) {
            return true;
        }

        // optimised to significantly lessen the number of SQL queries performed
        // when logged in as the user being checked.
        $user->getModeratorTokens()->get(-1);

        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('forum', $this));

        return \count($user->getModeratorTokens()->matching($criteria)) > 0;
    }

    public function addModerator(Moderator $moderator): void {
        if (!$this->moderators->contains($moderator)) {
            $this->moderators->add($moderator);
        }
    }

    public function userCanDelete($user): bool {
        if (!$user instanceof User) {
            return false;
        }

        if ($user->isAdmin()) {
            return true;
        }

        if (!$this->userIsModerator($user)) {
            return false;
        }

        return \count($this->submissions) === 0;
    }

    public function getSubmissionCount(): int {
        return \count($this->submissions);
    }

    public function addSubmission(Submission $submission): void {
        if ($submission->getForum() !== $this) {
            throw new \InvalidArgumentException(
                'Forum does not belong to submission',
            );
        }

        if (!$this->submissions->contains($submission)) {
            $this->submissions->add($submission);
        }
    }

    public function removeSubmission(Submission $submission): void {
        $this->submissions->removeElement($submission);
    }

    public function getCreated(): \DateTimeImmutable {
        return $this->created;
    }

    public function getSubscriptionCount(): int {
        return \count($this->subscriptions);
    }

    public function isSubscribed(User $user): bool {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('user', $user));

        return \count($this->subscriptions->matching($criteria)) > 0;
    }

    public function subscribe(User $user): void {
        if (!$this->isSubscribed($user)) {
            $this->subscriptions->add(new ForumSubscription($user, $this));
        }
    }

    public function unsubscribe(User $user): void {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('user', $user));

        $subscription = $this->subscriptions->matching($criteria)->first();

        if ($subscription) {
            $this->subscriptions->removeElement($subscription);
        }
    }

    public function userIsBanned(User $user): bool {
        if ($user->isAdmin()) {
            // should we check for mod permissions too?
            return false;
        }

        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('user', $user))

reddit_base_image_slim/postmill_app/src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Submission;
use App\Repository\TrashRepository;
use App\Repository\ForumRepository;
use App\SubmissionFinder\Criteria;
use App\SubmissionFinder\SubmissionFinder;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Response;

/**
 * Actions that list submissions across many forums.
 *
 * @Cache(smaxage="10 seconds")
 */
final class FrontController extends AbstractController {
    /**
     * @var ForumRepository
     */
    private $forums;

    /**
     * @var SubmissionFinder
     */
    private $submissionFinder;

    public function __construct(
        ForumRepository $forums,
        SubmissionFinder $submissionFinder
    ) {
        $this->forums = $forums;
        $this->submissionFinder = $submissionFinder;
    }

    public function front(?string $sortBy): Response {
        if ($this->isGranted('ROLE_USER')) {
            $user = $this->getUser();
            \assert($user instanceof \App\Entity\User);

            $listing = $user->getFrontPage();

            if (
                $listing === Submission::FRONT_SUBSCRIBED &&
                $user->getSubscriptionCount() === 0
            ) {
                $listing = Submission::FRONT_FEATURED;
            }
        } else {
            $listing = Submission::FRONT_FEATURED;
        }

        return $this->$listing($sortBy, 'html');
    }

    public function featured(?string $sortBy, string $_format): Response {
        $criteria = (new Criteria($sortBy))
            ->showFeatured()
            ->excludeBlockedUsers()
            ->excludeHiddenForums();

        $submissions = $this->submissionFinder->find($criteria);

        return $this->render("front/featured.$_format.twig", [
            'forums' => $this->forums->findFeaturedForumNames(),
            'sort_by' => $this->submissionFinder->getSortMode($sortBy),
            'submissions' => $submissions,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     */
    public function subscribed(?string $sortBy): Response {
        $forums = $this->forums->findSubscribedForumNames($this->getUser());

        if (!$forums) {
            // To avoid showing new users a blank page, we show them the
            // featured forums instead.
            return $this->redirectToRoute('featured', ['sortBy' => $sortBy]);
        }

        $criteria = (new Criteria($sortBy))
            ->excludeBlockedUsers()
            ->showSubscribed();

        $submissions = $this->submissionFinder->find($criteria);

        return $this->render('front/subscribed.html.twig', [
            'forums' => $forums,
            'sort_by' => $this->submissionFinder->getSortMode($sortBy),
            'submissions' => $submissions,
        ]);
    }

    public function all(?string $sortBy, string $_format): Response {
        $criteria = (new Criteria($sortBy))
            ->excludeBlockedUsers()
            ->excludeHiddenForums();

        $submissions = $this->submissionFinder->find($criteria);

        return $this->render("front/all.$_format.twig", [
            'sort_by' => $this->submissionFinder->getSortMode($sortBy),
            'submissions' => $submissions,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     */
    public function moderated(?string $sortBy): Response {
        $forums = $this->forums->findModeratedForumNames($this->getUser());

        $criteria = (new Criteria($sortBy))
            ->showModerated();

        $submissions = $this->submissionFinder->find($criteria);

        return $this->render('front/moderated.html.twig', [
            'forums' => $forums,
            'sort_by' => $this->submissionFinder->getSortMode($sortBy),
            'submissions' => $submissions,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     */
    public function trash(TrashRepository $trash): Response {
        $forums = $this->forums->findModeratedForumNames($this->getUser());

        return $this->render('front/trash.html.twig', [
            'forums' => $forums,
            'trash' => $trash->findTrashForUser($this->getUser()),
        ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     */
    public function globalTrash(TrashRepository $trash): Response {
        return $this->render('front/trash.html.twig', [
            'trash' => $trash->findTrash(),
        ]);
    }
}

reddit_base_image_slim/postmill_app/templates/front/_base.html.twig
{% extends 'base.html.twig' %}

{% from 'submission/_macros.html.twig' import submission %}
{% from '_macros/post_nav.html.twig' import front_post_types,
                                            submission_filter,
                                            submission_sort,
                                            submission_time %}

{% block site_nav_active 'front' %}

{% block head %}
  <link rel="canonical" href="{{ url('front') }}">

  <meta property="og:title" content="{{ site_name() }}">
  <meta property="og:site_name" content="{{ site_name() }}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ url('front') }}">
  <meta property="og:image" content="{{ absolute_url(asset('apple-touch-icon-precomposed.png')) }}">

  {{ include('_includes/meta_pagination.html.twig', { pager: submissions }, with_context=false) }}
{% endblock head %}

{% block body %}
  <nav class="flex flex--guttered">
    {% block front_post_nav %}
      {{ front_post_types('submissions') }}

      <ul class="unlistify flex">
        {{ submission_filter(block('listing'), sort_by) }}
        {{ submission_sort(sort_by) }}
        {{ submission_time(sort_by) }}
      </ul>
    {% endblock front_post_nav %}
  </nav>

  {% block front_alerts '' %}

  {% for submission in submissions %}
    {{ submission(submission) }}
  {% endfor %}

  {{ include('_includes/pagination.html.twig', { pager: submissions }, with_context=false) }}
{% endblock body %}

reddit_base_image_slim/postmill_app/templates/front/_moderator_nav.html.twig
{% set route = app.request.attributes.get('_route') %}
<div class="flex__grow"></div>
<ul class="unlistify flex">
  <li>
    <a href="{{ path('moderated') }}" class="tab {{ route == 'moderated' ? 'tab--active' }}">
      {{- 'nav.forums'|trans -}}
    </a>
  </li>
  <li>
    <a href="{{ path('trash') }}" class="tab {{ route == 'trash' ? 'tab--active' }}">
      {{- 'nav.trash'|trans -}}
    </a>
  </li>
</ul>

reddit_base_image_slim/postmill_app/templates/front/all.atom.twig
{% extends 'submission/_feed.atom.twig' %}

{% block title site_name() %}
{% block subtitle 'front.all_forums'|trans %}

reddit_base_image_slim/postmill_app/templates/front/all.html.twig
{% extends 'front/_base.html.twig' %}

{% block listing 'all' %}

reddit_base_image_slim/postmill_app/templates/front/featured.atom.twig
{% extends 'submission/_feed.atom.twig' %}

{% block title site_name() %}
{% block subtitle 'front.featured_forums'|trans %}

reddit_base_image_slim/postmill_app/templates/front/featured.html.twig
{% extends 'front/_base.html.twig' %}
{% from '_macros/alert.html.twig' import alert %}

{% block listing 'featured' %}

{% block front_alerts %}
  {% if is_granted('ROLE_USER') %}
    {% if app.user.frontPage == 'subscribed' and app.user.subscriptionCount == 0 %}
      {{ alert('front.no_subscriptions'|trans) }}
    {% endif %}
  {% endif %}
{% endblock front_alerts %}

{% block sidebar %}
  {{ parent() }}

  <section class="sidebar__section flow">
    <h1 class="sidebar__title">{{ 'front.featured_forums'|trans }}</h1>

    {% if forums|length > 0 %}
      <ul class="unlistify flex flex--guttered flex--slim-gutters">
        {% for name in forums %}
          <li>
            <a href="{{ path('forum', {forum_name: name}) }}"
               class="button button--secondary button--small">
              {{- name -}}
            </a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="fg-muted">
        <small class="text-sm">
          {{- 'front.no_forums'|trans -}}
        </small>
      </p>
    {% endif %}
  </section>
{% endblock sidebar %}

reddit_base_image_slim/postmill_app/templates/front/moderated.html.twig
{% extends 'front/_base.html.twig' %}
{% from '_macros/alert.html.twig' import alert %}
{% from '_macros/post_nav.html.twig' import submission_filter, submission_sort, submission_time %}

{% block listing 'moderated' %}

{% block body %}
  {% if forums is empty %}
    {{ alert('flash.no_moderated_forums'|trans) }}
  {% endif %}

  {{ parent() }}
{% endblock body %}

{% block front_post_nav %}
  {{ parent() }}
  {{ include('front/_moderator_nav.html.twig', with_context=false) }}
{% endblock %}

{% block sidebar %}
  {{ parent() }}

  {%- if forums|length > 0 -%}
    <section class="sidebar__section flow">
      <h1 class="sidebar__title">{{ 'heading.forums_you_moderate'|trans }}</h1>

      <ul class="unlistify flex flex--guttered flex--slim-gutters">
        {% for forum in forums %}
          <li>
            <a href="{{ path('forum', {forum_name: forum}) }}"
               class="button button--secondary button--small">
              {{- forum -}}
            </a>
          </li>
        {% endfor %}
      </ul>
    </section>
  {%- endif -%}
{% endblock sidebar %}

reddit_base_image_slim/postmill_app/templates/front/subscribed.html.twig
{% extends 'front/_base.html.twig' %}

{% block listing 'subscribed' %}

{% block sidebar %}
  {{ parent() }}

  <section class="sidebar__section flow">
    <h1 class="sidebar__title">{{ 'front.subscribed_forums'|trans }}</h1>

    <ul class="unlistify flex flex--guttered flex--slim-gutters">
      {% for name in forums %}
        <li>
          <a href="{{ path('forum', {forum_name: name}) }}"
             class="button button--secondary button--small">
            {{- name -}}
          </a>
        </li>
      {% endfor %}
    </ul>
  </section>
{% endblock sidebar %}

reddit_base_image_slim/postmill_app/templates/front/trash.html.twig
{% extends 'front/moderated.html.twig' %}
{% from '_macros/alert.html.twig' import alert %}
{% from 'comment/_macros.html.twig' import comment %}
{% from 'submission/_macros.html.twig' import submission %}

{% block title 'nav.trash'|trans %}

{% block head %}
  {{ include('_includes/pagination.html.twig', { pager: trash }, with_context=false) }}
{% endblock head %}

{% block body %}
  <nav class="flex flex--guttered">
    <h1>{{ 'nav.trash'|trans }}</h1>

    {{ include('front/_moderator_nav.html.twig', with_context=false) }}
  </nav>

  {{ alert('help.front_trash'|trans, 'info') }}

  {% for item in trash %}
    {% if item.title is defined %}
      {{ submission(item) }}
    {% else %}
      {{ comment(item, { show_context: true, show_trashed: true }) }}
    {% endif %}
  {% else %}
    <p class="fg-muted"><small class="text-md">{{ 'flash.no_entries_to_display'|trans }}</small></p>
  {% endfor %}

  {{ include('_includes/pagination.html.twig', { pager: trash }, with_context=false) }}
{% endblock body %}